config/routes.rb
Rails.application.routes.draw do
    root 'static_pages#home'
    get '/help', to: 'static_pages#help'
    get '/tuition', to: 'static_pages#tuition'
    get '/contactus', to: 'static_pages#contactus'
    get '/academic', to: 'static_pages#academic'
    get '/help', to: 'static_pages#help'
    get '/tricom', to: 'static_pages#tricom'
    get '/trisoftware', to: 'static_pages#trisoftware'
    get '/administration', to: 'static_pages#administration'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

protect_from_forgery with: :exception

def hello

render html: "hello, world!"

end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">

<div id="nav">
<small>




</small>

<nav>

<ul>

<a href="https://www.facebook.com/KasetsartCPE">
  <div style = "float : right;"><img src="http://icons.iconarchive.com/icons/paomedia/small-n-flat/256/social-facebook-icon.png" alt="faceb" style="width:40px;height:40px;border:0;"></div>
</a>
<a href="mailto:cpe@ku.ac.th">
  <div style = "float : right;"><img src="http://icons.iconarchive.com/icons/dtafalonso/android-l/128/Gmail-icon.png" alt="mail" style="width:40px;height:40px;border:0;"></div>
</a>
<a href="https://www.youtube.com/user/admissionengku">
  <div style = "float : right;"><img src="https://www.youtube.com/yt/brand/media/image/YouTube-icon-full_color.png" alt="youtube" style="width:35px;height:35px;border:0;"></div>
</a>

</ul>

</nav>
</div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Homepage</title>
   <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <img src="https://www.cpe.ku.ac.th/wp-content/uploads/2014/08/logo_blue2-1.jpg">
    <div id="nav">
        <div id="nav_wrapper">
            <ul>
                <li><%= link_to "Home",root_path %>
                </li>
                <li> <%= link_to "Academic",academic_path %>
                    <ul>
                        <li><%= link_to "Bachelor Degree of Computer Engineering",tricom_path %>
                        </li>
                        <li><%= link_to "Bachelor Degree of Software and Knowledge Engineering",trisoftware_path %>
                        </li>
                    </ul>
                </li>
                <li> <a href="#">Administration</a>

                    <ul>
                        <li><%= link_to "Department Heads",administration_path %>
                        </li>
                        <!--<li><a href="#">Seniors & Executive Members</a>-->
                        <!--</li>-->
                        <!--<li><a href="#">Staffs</a>-->
                        <!--</li>-->
                    </ul>
                </li>
                <!--<li> <a href="#">Admissions</a>-->

                <!--    <ul>-->
                <!--        <li><a href="#">How To Apply</a>-->
                <!--        </li>-->
                <!--        <li><a href="#">Statistical Data</a>-->
                <!--        </li>-->
                <!--    </ul>-->
                <!--</li>-->
                <li> <%= link_to "Tuition Fee",tuition_path %>
                </li>
                <li> <%= link_to "Contact Us",contactus_path %>
                </li>
                <li>
                    <form>
                        <input type="text"  name="search" placeholder="Search..">
                    </form>
                </li>
            </ul>
        </div>
    </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
</body>

</html>

app/views/static_pages/academic.html.erb
<div>
<h1>Academic</h1>
<br>
<p>ภาควิชาฯ ได้เปิดหลักสูตรเพื่อสนองความต้องการของประเทศจำนวน 5 หลักสูตร แบ่งเป็นหลักสูตรระดับปริญญาตรี 1 หลักสูตร หลักสูตรนานาชาติระดับปริญญาตรี 1 หลักสูตร หลักสูตรระดับปริญญาโท 2 หลักสูตร และหลักสูตรระดับปริญญาเอก 1 หลักสูตร คือ</p>
<br>
<li>หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิศวกรรมคอมพิวเตอร์</li>
<li>หลักสูตรวิศวกรรมศาสตรบัณฑิตนานาชาติ สาขาวิศวกรรมซอฟต์แวร์และความรู้</li>
<li>หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาเทคโนโลยีสารสนเทศ</li>
<li>หลักสูตรวิศวกรรมศาสตรมหาบัณฑิต สาขาวิศวกรรมคอมพิวเตอร์</li>
<li>หลักสูตรวิศวกรรมศาสตรดุษฎีบัณฑิต สาขาวิศวกรรมคอมพิวเตอร์</li>
<br>
<p>นอกจากนี้ภาควิชาฯ ยังให้ความร่วมมือในการสอนรายวิชาหลัก รายวิชารอง และรายวิชาเลือก ที่อยู่ในความชำนาญของภาควิชาฯ ดังได้กล่าวข้างต้น ให้แก่หลักสูตรอื่นๆ ทั้งที่เป็นของภาควิชาฯ ภายใต้คณะวิศวกรรมศาสตร์ ภาควิชาต่างคณะ และภาควิชาในต่างวิทยาเขต</p>
</div>

app/views/static_pages/administration.html.erb
<div>
<h1>Administration</h1>

<div style="text-align: center;">
  
  <p></p><img src ="https://www.cpe.ku.ac.th/wp-content/uploads/2015/01/Anan-New.jpg"><br/>Assoc. Prof. Anan  PHONPHOEM<br/>2014 – present</p><br/>
  <p></p><img src ="https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-8-8-30.jpg"><br/>Asst. Prof. Putchong  UTHAYOPAS<br/>2011 – 2014</p><br/>
  <p></p><img src ="https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-7-7-15.jpg"><br/>Asst. Prof. Kemathat VIBHATAVANIJ<br/>2006 – 2010</p><br/>
  <p></p><img src ="https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-45-45-25.jpg"><br/>Asst. Prof. Pirawat WATANAPONGSE<br/>2002 -2006</p><br/>
  <p></p><img src ="https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-2-2-24.jpg"><br/>Assoc. Prof. Pradondet  NILAGUPTA<br/>1999 – 2002</p><br/>
  <p></p><img src ="https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-18-18-6.jpg"><br/>Asst. Prof. Somnuk  KERETHO<br/>1996 – 1999</p><br/>
  <p></p><img src ="https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-14-14-13.jpg"><br/>Assoc. Prof. Chaiyong WONGCHAISUWAT<br/>1992 – 1999</p><br/>
  <p></p><img src ="https://www.cpe.ku.ac.th/wp-content/uploads/2015/06/รูปนนทวัฒน์สูท.jpg"><br/>Nontawat JUNJAREON<br/>1989  – 1992</p><br/>

</div>
</div>

app/views/static_pages/administration.htnl.erb
<div>
<h1>Administration</h1>

<div style="text-align: center;">
  
  <p></p><img src ="https://www.cpe.ku.ac.th/wp-content/uploads/2015/01/Anan-New.jpg"><br/>Assoc. Prof. Anan  PHONPHOEM<br/>2014 – present</p><br/>
  <p></p><img src ="https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-8-8-30.jpg"><br/>Asst. Prof. Putchong  UTHAYOPAS<br/>2011 – 2014</p><br/>
  <p></p><img src ="https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-7-7-15.jpg"><br/>Asst. Prof. Kemathat VIBHATAVANIJ<br/>2006 – 2010</p><br/>
  <p></p><img src ="https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-45-45-25.jpg"><br/>Asst. Prof. Pirawat WATANAPONGSE<br/>2002 -2006</p><br/>
  <p></p><img src ="https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-2-2-24.jpg"><br/>Assoc. Prof. Pradondet  NILAGUPTA<br/>1999 – 2002</p><br/>
  <p></p><img src ="https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-18-18-6.jpg"><br/>Asst. Prof. Somnuk  KERETHO<br/>1996 – 1999</p><br/>
  <p></p><img src ="https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-14-14-13.jpg"><br/>Assoc. Prof. Chaiyong WONGCHAISUWAT<br/>1992 – 1999</p><br/>
  <p></p><img src ="https://www.cpe.ku.ac.th/wp-content/uploads/2015/06/รูปนนทวัฒน์สูท.jpg"><br/>Nontawat JUNJAREON<br/>1989  – 1992</p><br/>

</div>
</div>

app/views/static_pages/contactus.html.erb
<div>
<h1>Contact Us</h1>
<br>
<br>
<hr width="80%" color="gray">
<br>
<br>
<p>ภาควิชาวิศวกรรมคอมพิวเตอร์ คณะวิศวกรรมศาสตร์ มหาวิทยาลัยเกษตรศาสตร์ (วิทยาเขตบางเขน)</p>
<p>เลขที่ 50 ถนนงามวงศ์วาน แขวงลาดยาว</p>
<p>เขตจตุจักร กรุงเทพ ฯ 10900</p><br>
<p>โทร. 0-2797-0999 ต่อ 1403-04 1450</p><br>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15296.156474927724!2d100.56942579810745!3d13.846088836168404!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x30e29cde06012b57%3A0xf0100b33d0b3170!2sKasetsart+University!5e0!3m2!1sen!2sus!4v1495694255577" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>

app/views/static_pages/help.html.erb
<div>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>
</div>

app/views/static_pages/home.html.erb
<body>
<img src ="http://www.ku.ac.th/web2012/resources/upload/content/1353916683_img.jpg" alt="ku engineer pic" style="width: 100%; height: 480px;">

<h2>!! News !!</h2>
<h3>“KuAcar” คว้าอันดับ2 การแข่งขันรถจำลองไร้คนขับ AMAS MBD 2016</h3>

<div style="width:500px; margin:0 auto;">
  <img class="mySlides" src="https://www.cpe.ku.ac.th/wp-content/gallery/kuacar/16837886_10154867331038046_691987547_n.jpg" style="width:480px ; height: 400px;">
  <img class="mySlides" src="https://www.cpe.ku.ac.th/wp-content/gallery/kuacar/16923594_10154867331058046_2127900613_n.jpg" style="width:480px ; height: 400px;">
  <img class="mySlides" src="https://www.cpe.ku.ac.th/wp-content/gallery/kuacar/16838027_10154867331053046_1348097201_n.jpg" style="width:480px ; height: 400px;">
  <img class="mySlides" src="https://www.cpe.ku.ac.th/wp-content/gallery/kuacar/16810571_10154867331123046_735667844_o.jpg" style="width:480px ; height: 400px;">
</div>


<p>“KuAcar” คว้าอันดับ2 การแข่งขัน AMAS MBD 2016 วันที่19 กุมภาพันธ์ 2560 ณ สำนักงานนวัตกรรมแห่งชาติ   การแข่งขัน AMAS MBD 2016 เป็นการแข่งขันรถจำลองไร้คนขับ โดยสั่งงานผ่านระบบซอฟต์แวร์ระบบสมองกลฝังตัวไปยังรถจำลอง (Embedded Software) ที่ใช้การพัฒนาแบบ Model Based Development ซึ่งเป็นเทคโนโลยีที่ใช้ในการพัฒนาซอฟต์แวร์ในรถยนต์ในปัจจุบัน และอนาคต โครงการนี้ได้จัดขึ้นเป็นครั้งแรกของประเทศไทย โดยแต่ละทีมมีเวลาในการพัฒนาซอฟต์แวร์ระบบสมองกลฝังตัว ใส่ความคิดสร้างสรรค์ และทดสอบระบบดังกล่าวกัน 1 ภาคการศึกษา สมาชิกทีม KuAcar ประกอบด้วย</p>
<div class = "name">
<li>นาย ศุภกฤษฏิ์ เกรียงขจร</li> 
<li>นาย วสุธร ศิริยากร</li>
<li>นาย ณัฐชนันท์ ทองเต็ม</li>
</div>

<p>มีผศ.ดร. ยอดเยี่ยม ทิพย์สุวรรณ เป็นอาจารย์ที่ปรึกษา โดยทั้งหมดเป็นนิสิตชั้นปีที่ 2 สาขาวิศวกรรมคอมพิวเตอร์</p>

<script>
var myIndex = 0;
carousel();

function carousel() {
    var i;
    var x = document.getElementsByClassName("mySlides");
    for (i = 0; i < x.length; i++) {
       x[i].style.display = "none";  
    }
    myIndex++;
    if (myIndex > x.length) {myIndex = 1}    
    x[myIndex-1].style.display = "block";  
    setTimeout(carousel, 3000); // Change image every 3 seconds
}
</script>


</body>

app/views/static_pages/tricom.html.erb
<div>
<h1>ปริญญาตรีสาขาวิศวกรรมคอมพิวเตอร์</h1>
<br>
<h1>ชื่อปริญญา</h1>
<br>
<p>ชื่อเต็ม : วิศวกรรมศาสตรบัณฑิต (วิศวกรรมคอมพิวเตอร์)</p>
<p>ชื่อย่อ    : วศ.บ. (วิศวกรรมคอมพิวเตอร์)</p>
<p>ชื่อเต็ม  : Bachelor of Engineering (Computer Engineering)</p>
<p>ชื่อย่อ    : B.Eng. (Computer Engineering)</p>
<br>
<h1>หลักสูตร<h1>
<br>
<p>จำนวนหน่วยกิตรวมตลอดหลักสูตร ไม่น้อยกว่า 141 หน่วยกิต</p>
<br>
<h1>โครงสร้างหลักสูตร</h1>
<br>
<p>1.หมวดวิชาศึกษาทั่วไป ไม่น้อยกว่า 30 หน่วยกิต</p>
<li>กลุ่มวิชาวิทยาศาสตร์และคณิตศาสตร์ 10 หน่วยกิต</li>
<li>กลุ่มวิชาภาษา 12 หน่วยกิต</li>
<li>กลุ่มวิชาสังคมศาสตร์ 3 หน่วยกิต</li>
<li>กลุ่มวิชามนุษยศาสตร์ 3 หน่วยกิต</li>
<li>กลุ่มวิชาพลศึกษา 2 หน่วยกิต</li>
<p>2.หมวดวิชาเฉพาะ ไม่น้อยกว่า 105 หน่วยกิต<p>
<li>วิชาแกน 21 หน่วยกิต</li>
<li>วิชาเฉพาะบังคับ 66 หน่วยกิต</li>
<li>วิชาเฉพาะเลือก 18 หน่วยกิต</li>
<p>3.หมวดวิชาเสรีไม่น้อยกว่า 6 หน่วยกิต </p>
<p>การฝึกงาน ไม่น้อยกว่า 240 ชั่วโมง (ไม่นับหน่วยกิต)</p>
</div>

app/views/static_pages/trisoftware.html.erb
<div></div>
<h1>ปริญญาตรีสาขาวิศวกรรมซอฟต์แวร์และความรู้</h1>
<br>
<h1>ชื่อปริญญา</h1>
<br>
<p>ชื่อเต็ม : วิศวกรรมศาสตรบัณฑิต (วิศวกรรมซอฟต์แวร์และความรู้)</p>
<p>ชื่อย่อ :  วศ.บ. (วิศวกรรมซอฟต์แวร์และความรู้)</p>
<p>ชื่อเต็ม  : Bachelor of Engineering (Software and Knowledge Engineering)</p>
<p>ชื่อย่อ    : B.Eng. (Software and Knowledge Engineering)</p>
<br>
<h1>หลักสูตร<h1>
<br>
<p>จำนวนหน่วยกิตรวมตลอดหลักสูตร ไม่น้อยกว่า 136 หน่วยกิต</p>
<br>
<h1>โครงสร้างหลักสูตร/h1>
<br>
<p>1.หมวดวิชาศึกษาทั่วไป ไม่น้อยกว่า 30 หน่วยกิต</p>
<li>กลุ่มวิชาวิทยาสตร์และคณิตศาสตร์ 10 หน่วยกิต</li>
<li>กลุ่มวิชาภาษา 12 หน่วยกิต</li>
<li>กลุ่มวิชาสังคมศาสตร์ 3 หน่วยกิต</li>
<li>กลุ่มวิชามนุษยศาสตร์ 3 หน่วยกิต</li>
<li>กลุ่มวิชาพลศึกษา 2 หน่วยกิต</li>
<p>2.หมวดวิชาเฉพาะ ไม่น้อยกว่า 100 หน่วยกิต<p>
<li>วิชาเฉพาะบังคับ 88 หน่วยกิต</li>
<li>วิชาเฉพาะเลือกไม่น้อยกว่า 12 หน่วยกิต</li>
<p>3.หมวดวิชาเลือกเสรีไม่น้อยกว่า 6 หน่วยกิต </p>
</div>

app/views/static_pages/tuition.html.erb
<div>
<h1>Tuition fee and Scholarships</h1>
<br>
<p>การศึกษาเป็นการลงทุนอย่างหนึ่ง ผู้ที่สนใจเข้าศึกษาต่อและนิสิตปัจจุบันนอกจากจะต้องลงทุนทั้งทางด้านเวลาในการเข้ามาศึกษาหาความรู้เพิ่มเติมกับทางเราแล้วนั้น นิสิตในสังกัดภาควิชาวิศวกรรมคอมพิวเตอร์จะต้องจ่ายค่าลงทะเบียนและค่าธรรมเนียมอื่นๆตามที่มหาวิทยาลัยกำหนด</p>
<br>
<p>สำหรับผู้ที่สนใจเข้าศึกษาต่อและนิสิตปัจจุบันที่มีผลการเรียนดีเป็นพิเศษ และ/หรือ มีความขาดแคลนทางด้านทุนทรัพย์ ทางหน่วยงานต่างๆตั้งแต่ระดับมหาวิทยาลัย คณะวิศวกรรมศาสตร์ และภาควิชาวิศวกรรมคอมพิวเตอร์มีทุนการศึกษาเพื่อรองรับด้วยเช่นกัน</p>
<br>
<li><a href="http://www.regweb.registrar.ku.ac.th/calendar/index/138?a_id=218">ค่าลงทะเบียนและค่าธรรมเนียม</a></li>
<li>ทุนการศึกษา</li>
<br>
อัพเดทล่าสุด: 24/02/2015
<br>
<p>หมายเหตุ: ข้อมูลที่หน้านี้เป็นข้อมูลเพื่อใช้ในการอ้างอิงทั่วไปสำหรับผู้ที่สนใจเข้าศึกษาต่อและนิสิตปัจจุบันเท่านั้น อัตราค่าลงทะเบียนและค่าธรรมเนียมมีการเปลี่ยนแปลงจากทางมหาวิทยาลัยทุกปี ดังนั้นผู้สนใจโปรดตรวสอบข้อมูลกับทางมหาวิทยาลัยเพื่อความแน่นอนอีกครั้ง</p>
</div>